src/distribution/customer/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.upload_data, name='customer-data'),
]

src/distribution/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from .customer.urls import urlpatterns as customer_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(customer_urls, namespace='customer')),
]

src/distribution/customer/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/distribution/customer/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse
from .utils import get_customer_data, get_details, get_customer_order_count

def upload_data(request):
    order_count, amount, customer_order_count = get_customer_data()
    ordered_once, ordered_twice, ordered_thrice, ordered_fourtimes, ordered_higher = get_customer_order_count(
    																			customer_order_count) 		
    customer_order_count = sorted(customer_order_count.items(), key = lambda x:x[1])
    ctx = {
        'customer_order_count':customer_order_count,
    	'order_count':order_count,
    	'amount':amount,
    	'ordered_once' : ordered_once
    }
    return TemplateResponse(request, 'customer/list.html', ctx)

src/templates/customer/base.html
<!DOCTYPE html>
<html>
<head>
  <title>
    {% block title %}
    Honey Badger Labs
    {% endblock %}
  </title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
body {
    line-height: 1.5;
    font-family: Roboto, sans-serif;
    font-weight: 400;
    color: rgba(0, 0, 0, .87);
}
.main {
    margin-left: 200px;
    font-size: 12px;
    padding: 0px 10px;
}
.sidenav {
  height: 100%;
  width: 183px;
  position: fixed;
  z-index: 1;
  top: 52px;
  left: 0;
  background-color: #efe8e8;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 37px;
  text-decoration: none;
  font-size: 20px;
  color: #0c0c0c;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 200px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Honey Badger Labs</a>
    </div>
  </div>
</nav>
<div class="sidenav">
  <a href="{% url 'customer:customer-data' %}">List</a>
</div>

<main class="main">
  <div class="container">
    {% block content %}{% endblock %}
  </div>
</main>
   
</body>
</html> 

src/templates/customer/list.html
{% extends "customer/base.html" %}
{% block title %}Customers Data{% endblock %}
{% block body_class %}body-orders{% endblock %}
{% block menu_customer_class %}active{% endblock %}
{% block content %}
<style type="text/css">
  .main {
    margin-left: 200px;
    font-size: 16px;
    padding: 0px 0px;
  }
</style>
<div class = "card">
  <table class="table table-striped" style="border: 0.05rem gray solid;">
      <thead>
        <tr>
          <th>S.No</th>
          <th>Name</th>
          <th>Amount</th>
          <th>No of Orders</th>
        </tr>
      </thead>
      {% for key, value in customer_order_count %}    
      <tbody>
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{key}}</td>
          <td>{{value.ordered_amount}}</td>
          <td>{{ value.count}}</td>
        </tr>
      </tbody>
      {% endfor %}
  </table>
</div>
{% endblock %}